import {
  Sparkles, Bed, Utensils, BookOpen, Star, Heart, Leaf, Sun, Moon,
  Zap, Music, Paintbrush, ShoppingCart, Shirt, Trash2, Droplets,
  Baby, Dog, Cat, Fish, Bike, Dumbbell, Apple, Pizza, Car,
  Home, Flower2, Scissors, Wrench, Gamepad2, Tv, Laptop, Phone,
  Check, X, Plus, Clock,
  type LucideIcon
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  bed: Bed,
  utensils: Utensils,
  book: BookOpen,
  'book-open': BookOpen,
  star: Star,
  heart: Heart,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  zap: Zap,
  music: Music,
  brush: Paintbrush,
  paintbrush: Paintbrush,
  'shopping-cart': ShoppingCart,
  shirt: Shirt,
  trash: Trash2,
  trash2: Trash2,
  droplets: Droplets,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  fish: Fish,
  bike: Bike,
  dumbbell: Dumbbell,
  apple: Apple,
  pizza: Pizza,
  car: Car,
  home: Home,
  flower: Flower2,
  scissors: Scissors,
  wrench: Wrench,
  gamepad: Gamepad2,
  tv: Tv,
  laptop: Laptop,
  phone: Phone,
  check: Check,
  x: X,
  plus: Plus,
  clock: Clock,
}

export const CHORE_ICON_OPTIONS = [
  { value: 'sparkles', label: 'Sparkles' },
  { value: 'bed', label: 'Bed' },
  { value: 'utensils', label: 'Utensils' },
  { value: 'book', label: 'Book' },
  { value: 'star', label: 'Star' },
  { value: 'heart', label: 'Heart' },
  { value: 'leaf', label: 'Leaf' },
  { value: 'sun', label: 'Sun' },
  { value: 'moon', label: 'Moon' },
  { value: 'zap', label: 'Zap' },
  { value: 'music', label: 'Music' },
  { value: 'brush', label: 'Brush' },
  { value: 'shopping-cart', label: 'Shopping' },
  { value: 'shirt', label: 'Shirt' },
  { value: 'trash', label: 'Trash' },
  { value: 'droplets', label: 'Droplets' },
  { value: 'dog', label: 'Dog' },
  { value: 'dumbbell', label: 'Exercise' },
  { value: 'apple', label: 'Food' },
  { value: 'home', label: 'Home' },
]

export function getChoreIcon(iconName: string): LucideIcon {
  return ICON_MAP[iconName?.toLowerCase()] || Sparkles
}
